services:
  - type: web
    name: punch-clock
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app:app
    envVars:
      - key: FLASK_ENV
        value: production
